[build]
  # Directorio base donde est치 el proyecto
  base = "part2/phonebook"
  
  # Comando para construir el proyecto
  command = "npm run build"
  
  # Directorio donde se generan los archivos de producci칩n (relativo al base)
  publish = "dist"

[build.environment]
  # Versi칩n de Node.js a usar
  NODE_VERSION = "18"

# Configuraci칩n de redirects para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
